config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
    validates :image, presence: true
    validates :content, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
    validates :email, uniqueness: true, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  def set_post
     @post = Post.find(params[:id])
  end

  def post_params
     params.require(:post).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    end
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to posts_path
        else
        flash[:danger] = 'Failed to login'
        render :new
        end
    end
    def destroy
        session.delete(:user_id)
        flash[:notice] = 'You logged out'
        redirect_to new_session_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to user_path(@user.id)
      else
        render :new
      end
    end
    def show
      @user = User.find(params[:id])
    end
    private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
  <head>
    <title>Facebookclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class= "header">
    <h2> Facebook </2>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="top">
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    </div>
    <%= yield %>
    <footer>
      <p>© 2020 Copyright Facebook_clone </p>
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: choose_new_or_edit) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.image.url, size: 17*17) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>


  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/comfirm.html.erb
<div class="container">
<h1>Confirmation screen</h1>
<%= form_with(model: @post, url: posts_path , local: true) do |form| %>
  <%= image_tag(@post.image.url, size: 20*20) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>Content:<%= @post.content %></p>

  <%= form.submit "Post" %>

<% end %>
 <br>
<%= form_with(model:@post, url: new_post_path, local:true, method: 'get') do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "Return", name: "back" %>
<% end %>
</div>

app/views/posts/confirm.html.erb
<div class="container">
<h1>Confirmation screen</h1>
<%= form_with(model: @post, url: posts_path , local: true) do |form| %>
  <%= image_tag(@post.image.url, size: 20*20) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>Content:<%= @post.content %></p>

  <%= form.submit "Post" %>

<% end %>
 <br>
<%= form_with(model:@post, url: new_post_path, local:true, method: 'get') do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "Return", name: "back" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= image_tag post.image.url, style:"width:250px" %></td>
        <td><%= post.content %></td>
        <td><button type="button" class="btn btn-secondary"><%= link_to 'Show', post %></button></td>
        <td><button type="button" class="btn btn-secondary"><%= link_to 'Edit', edit_post_path(post) %></button></td>
        <td><button type="button" class="btn btn-secondary"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-success"><%= link_to 'New Post', new_post_path %></button>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url, style:"width:350px" %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/users/new.html.erb
<div class="container">
<h1>Sign up</h1>
<table class="table">
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
<tr>
  <td>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </td></tr>
<tr>
  <td>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </td></tr>
<tr>
  <td>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </td></tr>
  <tr>
   <td>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </td></tr>
  <tr style="background-color:#3498DB">
    <td>
  <%= f.submit "Create my account" %>
  </td></tr>
</div>
</table>
<% end %>

app/views/users/show.html.erb
<div class="container">
<h1><%= @user.name %>'s facebook page</h1>
<h3>email address: <%= @user.email %></h>
<hr>
<% if logged_in? %>
  <%= link_to 'View posts', posts_path %>
<%else%>
  <%= link_to 'Log in', new_session_path%>
<%end%>
</div>